version: "3.2"
services:
    db:
        image: mongo:3.4-jessie
        volumes:
            - ./db:/data/db
            - ./configdb:/data/configdb
        ports:
            - "127.0.0.1:20722:27017"
    mailcatcher:
        image: schickling/mailcatcher:latest
        ports:
            - "127.0.0.1:1080:1080"
            - "127.0.0.1:1025:1025"
